# -*- coding: utf-8 -*-
"""gpt-neo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgS9gvVXfkZr6oGV1THKU9pqggJmrnTT

**bold text**# Run GPT-Neo

### Install Happy Transformer
https://github.com/EricFillion/happy-transformer
"""

from google.colab import drive
drive.mount('/content/drive')

pip install happytransformer

"""### Import HappyGeneration"""

from happytransformer import HappyGeneration

"""### Create a HappyGeneration Object """

happy_gen = HappyGeneration("GPT-NEO", "EleutherAI/gpt-neo-125M")

"""## happy_gen.generate_text()"""







"""### import GENSettings"""



"""### Greedy"""









"""### Generic Samping"""







"""### Top-k Sampling"""







"""### GPT-2"""





